import svelte from "@astrojs/svelte";
import { paraglideVitePlugin } from "@inlang/paraglide-js";
import playformCompress from "@playform/compress";
import tailwindcss from "@tailwindcss/vite";
import astroPWA from "@vite-pwa/astro";
import stripWhitespace from "astro-strip-whitespace";
import { defineConfig } from "astro/config";
import macros from "unplugin-macros/vite";
import {
  baseLocale,
  locales,
} from "./project.inlang/settings.json" with { type: "json" };

// https://astro.build/config
export default defineConfig({
  site: process.env.SITE_URL ?? "https://bakezip.roundtrip.dev",
  i18n: {
    locales: locales,
    defaultLocale: baseLocale,
    routing: {
      prefixDefaultLocale: false,
    },
  },
  integrations: [
    astroPWA({
      base: "/",
      scope: "/",
      registerType: "autoUpdate",
      injectRegister: "auto",
      includeAssets: ["favicon.svg"],
      manifest: {
        id: "/",
        start_url: "/pwa",
        lang: "en",
        name: "BakeZip",
        short_name: "BakeZip",
        description: "Inspect, rebuild, and repair ZIPs in your browser.",
        icons: [
          {
            src: "pwa-64x64.png",
            sizes: "64x64",
            type: "image/png",
          },
          {
            src: "pwa-192x192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "pwa-512x512.png",
            sizes: "512x512",
            type: "image/png",
          },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        // @ts-expect-error _localized fields are not yet typed in vite-plugin-pwa
        description_localized: {
          en: "Inspect, rebuild, and repair ZIPs in your browser.",
          ja: "ブラウザでZIPを検査、再構築、修復します。",
          ko: "브라우저에서 ZIP을 검사, 재구성 및 복구합니다.",
          "zh-CN": "在浏览器中检查、重建和修复ZIP文件。",
          "zh-TW": "在瀏覽器中檢查、重建和修復ZIP檔案。",
        },
        display: "standalone",
      },
      workbox: {
        globPatterns: ["**/*.{js,css,html,ico,png,svg,wasm}"],
        runtimeCaching: [
          {
            urlPattern: ({ request }) => request.destination === "document",
            handler: "NetworkFirst",
            options: {
              cacheName: "html-cache",
              networkTimeoutSeconds: 3,
              expiration: {
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24 * 7,
              },
            },
          },
          {
            urlPattern: ({ request }) =>
              request.destination === "script" ||
              request.destination === "style" ||
              request.destination === "worker",
            handler: "StaleWhileRevalidate",
            options: {
              cacheName: "asset-cache",
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 60 * 60 * 24 * 30,
              },
            },
          },
          {
            urlPattern: ({ request, url }) =>
              request.destination === "image" || url.pathname.endsWith(".wasm"),
            handler: "CacheFirst",
            options: {
              cacheName: "static-cache",
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 * 30,
              },
            },
          },
        ],
      },
    }),
    playformCompress({
      HTML: {
        "html-minifier-terser": {
          caseSensitive: false,
          collapseBooleanAttributes: false,
          collapseInlineTagWhitespace: false,
          collapseWhitespace: false,
          conservativeCollapse: false,
          customAttrAssign: [],
          customAttrCollapse: /^NEVER$/,
          customAttrSurround: [],
          customEventAttributes: [],
          decodeEntities: false,
          ignoreCustomComments: [],
          ignoreCustomFragments: [],
          includeAutoGeneratedTags: false,
          keepClosingSlash: false,
          noNewlinesBeforeTagClose: false,
          preserveLineBreaks: false,
          preventAttributesEscaping: false,
          removeAttributeQuotes: false,
          removeComments: false,
          removeEmptyAttributes: false,
          removeEmptyElements: false,
          removeOptionalTags: false,
          removeRedundantAttributes: false,
          removeScriptTypeAttributes: false,
          removeStyleLinkTypeAttributes: false,
          removeTagWhitespace: false,
          trimCustomFragments: false,
        },
      },
      SVG: {
        svgo: {
          plugins: [
            {
              name: "preset-default",
              params: {
                overrides: {
                  inlineStyles: false,
                },
              },
            },
          ],
        },
      },
    }),
    svelte(),
    stripWhitespace(),
  ],
  vite: {
    plugins: [
      macros(),
      paraglideVitePlugin({
        project: "./project.inlang",
        outdir: "./src/paraglide",
      }),
      tailwindcss(),
    ],
    server: {
      watch: {
        ignored: ["**/crates/**", "**/target/**"],
      },
    },
  },
});
